export const pages = [
    { path: "title.html",             title: "Title" },
    { path: "what-is-geekpresent.html", title: "What is GeekPresent?" },
    { path: "project-structure.html", title: "Project Structure" },
    { path: "title-page.html",        title: "Using TitlePage" },
    { path: "content-page.html",      title: "Using ContentPage" },
    { path: "navigation.html",        title: "Navigation" },
    { path: "components.html",        title: "Components" },
    { path: "box-component.html",     title: "Box Component" },
    { path: "youtube-showcase.html",  title: "YouTube" },
    { path: "hint-component.html",    title: "Hint" },
    { path: "label-component.html",   title: "Label" },
    { path: "widediv-component.html", title: "WideDiv" },
    { path: "code-component.html",    title: "Code" },
    { path: "javacode-component.html", title: "JavaCode" },
    { path: "codebox-component.html", title: "CodeBox" },
    { path: "javacodebox-component.html", title: "JavaCodeBox" },
    { path: "speaker-notes.html",     title: "Speaker Notes" },
    { path: "keyboard-shortcuts.html", title: "Keyboard Shortcuts" },
    { path: "thank-you.html",         title: "Thank You" },
];
