#!/bin/bash
set -e
# Generated by: booth init new --select nodejs+vscode-ext+pnpm-install/claude-code+auto-accept --port 6000
# Adjust with : booth init adjust --port 6000 --select nodejs+vscode-ext+pnpm-install/claude-code+auto-accept

# Restore pre-installed node_modules from image cache if missing
if [ -d /opt/pnpm-cache/node_modules ] && [ ! -d node_modules ]; then
  echo "📦 Restoring cached node_modules ..."
  cp -a /opt/pnpm-cache/node_modules .
fi
# Detect user-bound volumes and protect them from accidental rm -rf
# by patching Claude Code's deny rules with jq.
settings="$HOME/.claude/settings.json"
if [ -f "$settings" ] && command -v jq &>/dev/null; then
    # Collect non-system mount points from mountinfo.
    # These are likely user-bound persistent volumes.
    protected=$(awk '{print $5}' /proc/self/mountinfo 2>/dev/null | sort -u | grep -v -xE '/' | grep -v -E '^/(proc|sys|dev|run|tmp)(/|$)' | grep -v -E '^/etc/(resolv\.conf|hostname|hosts)$' || true)
    if [ -n "$protected" ]; then
        deny_rules='[]'
        while IFS= read -r mp; do
            deny_rules=$(echo "$deny_rules" | jq --arg p "$mp" '. + ["Bash(rm -rf \($p))", "Bash(rm -rf \($p)/*)"]')
        done <<< "$protected"
        jq --argjson new_deny "$deny_rules" '
            .permissions.deny = ((.permissions.deny // []) + $new_deny | unique)
        ' "$settings" > "${settings}.tmp" && mv "${settings}.tmp" "$settings"
    fi
fi
